### ISSUE TITLE
Tokenization of dashes is non-standard

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_Bulgarian-BTB#9]
There are quite a few dashes in this treebank which do not split words, which is different from the English treebanks, for example.  Is this something that can be standardized?

**Comment by martinpopel** [comment]
I see no dashes (en-dash nor em-dash) inside words in the data, just hyphens. The ten most common such word forms (and their lemmas and number of occurrences) are:

         'по-късно|късно': 24,
         'д-р|д-р': 23,
         'по-малко|малко': 20,
         'по-голяма|голям': 18,
         'г-н|господин': 18,
         'ИТАР-ТАСС|итар-тасс': 12,
         'най-много|много': 11,
         'Г-н|господин': 11,
         'по-добре|добре': 11,
         'по-голямо|голям': 10,

Before inspecting these cases, note that UD has not fully harmonized guidelines for tokenization and lemmatization.

* по- and най- are prefixes for comparative and superlative, which are written with the hyphen in standard Bulgarian orthography. (Note that English_EWT treats e.g. *post-war* or *mid-July* as a single word.)
* д-р is an abbreviation of доктор (doctor), г-н is an abbreviation of господин (Mr, sir,...). Here the **lemmatization seems to be inconsistent** in whether to use the full form or abbreviation as the lemma. Such abbreviations are common in Bulgarian, but we can see such [contraction type](https://en.wikipedia.org/wiki/Abbreviation#Periods_(full_stops)_and_spaces) of abbreviations also in English, e.g. *e-mail* instead of *electronic mail*.
* ИТАР-ТАСС is [ITAR-TASS](https://en.wikipedia.org/wiki/TASS), which is a name of a single entity. I find it strange that the **lemma is lowercased**. Note that English_GUM annotates e.g. *CC-BY-SA-NC* as a single word.

So in these cases, I think the tokenization is OK (and consistent with English), just the lemmatization may be questionable as highlighted in bold above. Of course, there may be also some questionable tokenization issues in Bulgarian, e.g. GSM-оператор (GSM operator).

**Comment by AngledLuffa** [comment]
Thanks for the detailed reply!  I saw some of these cases, of course, but
without knowing Bulgarian I was unsure about how they were best handled.

The issue I'm running into, in case you can advise on this at all, is that
our tokenizer keeps *all* hyphens (thank you for that correction) in one
token when processing novel text.  For example, I picked up the bsnlp NER
dataset to build an NER model for Bulgarian, and these are some of the
examples our tokenizer leaves as one chunk:

който ограничава правото на движение на гражданите на Обединеното кралство
в ЕС-27 след Брекзит
... maybe that would also be interpreted as one token here

 вече са преминали граничния пункт при Видин-Калафат.
I would expect these two cities to be separate tokens, but there are no
examples like this in the BTB training set that I could find, and the
result is the tokenizer generalizes to keep them as one token.

How would you suggest tokenizing these two examples?  Thanks

**Comment by martinpopel** [comment]
> ЕС-27

I think it should be a single word, similarly to [EU-27](https://en.wikipedia.org/wiki/EU_27) in English. This seems especially useful for NER.

> пункт при Видин-Калафат

Here I can imagine both analyses. It could be a name of a bridge or a checkpoint (although probably not in this sentence, which says "a checkpoint **by/at** Vidin-Kalafat"). Either way, the name origins from the two cities.

There are many types of name-name hyphen compounds. UD is not consistent in whether these should be a single word or two words, even within the same type. E.g. English_EWT treats them almost always as three words, while English-GUM as a single word.

**Comment by amir-zeldes** [comment]
> English_EWT treats them almost always as three words, while English-GUM as a single word

In GUM the two cities case would also be three tokens, here are some examples:

https://corpling.uis.georgetown.edu/annis/#_q=eHBvcz0iTk5QIiAuICItIiAuIHhwb3M9Ik5OUCI&_c=R1VN&cl=5&cr=5&s=0&l=10

Non-split cases in GUM are ones where the hyphenation is understood to be inside a morphological unit below the word level, like derived or compound adjectives ("non-representative", "form-related"), compound nouns spelled together ("eye-tracking") or fixed terms containing hyphens ("p-value"). 

EWT tokenizes hyphens more liberally, but still keeps some things together like: "over-rated", "non-commercial", "mid-80s". I think "eye-tracking" and "form-related" would probably be split in EWT.

**Comment by martinpopel** [comment]
What I meant ‎was that GUM treats e.g. `/Al-.*‎/` names as a single word, while EWT separates the definite article and hyphen.
Compare also the number of occurrences of `‎/[A-Z][a-z]+-[A-Z][a-z]+‎/` in EWT and GUM.
Anyway, I think we should close this issue (and maybe open new issues about lemmatization in BTB and tokenization inconsistencies in EWT-vs-GUM.

**Comment by AngledLuffa** [comment]
Sounds good to me.  Thanks for the clarifications!
